### ISSUE TITLE
Knockouts don't work for: Basetype Arrays

### ISSUE THREAD

**Issue by raandree** [gaelcolas/datum#127]
It is not documented but one would expect that removing values using the knockout prefix would work with base type arrays.

Windows Features defined in the role:
```yml
WindowsFeatures:
  Names:
    - File-Services
    - Feature1
```

Windows Features defined on the node:
```yml
WindowsFeatures:
  Names:
    - --Feature1
```

Actual RSOP:
```yml
WindowsFeatures:
  Names:
  - File-Services                                                                               AllNodes\Dev\DSCFile01
  - --Feature1                                                                                  AllNodes\Dev\DSCFile01
  - Feature1                                                                                          Roles\FileServer
  - -Telnet-Client                                                                                  Baselines\Security
```

Expected RSOP:
```yml
WindowsFeatures:
  Names:
  - File-Services                                                                               AllNodes\Dev\DSCFile01
  - -Telnet-Client                                                                                  Baselines\Security
```

The `datum.yml` definition for merging and knockout looks like this:

```yml
WindowsFeatures:
  merge_hash: deep
WindowsFeatures\Names:
  merge_basetype_array: Unique
  merge_options:
    knockout_prefix: --
```

I am currently working on code to make this working.
