### ISSUE TITLE
Knockouts don't work for: Hashtables

### ISSUE THREAD

**Issue by raandree** [gaelcolas/datum#128]
Knockouts don't work as expected / produce unexpected results assuming that 'knockout_prefix' is implemented similar like in Puppet. There is not much documentation and descriptions in Puppet and the best summary of that feature is on [StackOverflow: Using knockout_prefix in puppet hiera hierarchy](https://stackoverflow.com/questions/35887394/using-knockout-prefix-in-puppet-hiera-hierarchy):

Lower Level:
```yml
Car:
  Brand: VW
  Model: Golf
  Engine:
    Volume: 2.0
```

Higher Level:
```yml
Car:
  --Model:
  Color: Red
  Engine:
    Type: Gasoline
```

RSOP:
```yml
Car:
  Color: Red                                                                                    AllNodes\Dev\DSCFile01
  --Model: 
  Engine:
    Type: Gasoline                                                                              AllNodes\Dev\DSCFile01
    Volume: 2                                                                                         Roles\FileServer
  Brand: VW
```

Datum.yml
```yml
  Car:
    merge_hash: deep
    merge_options:
      knockout_prefix: --
```

The key model was knocked out but the key for knocking out is added to the result. This is not expected and results in errors when splatting the hashtable to the DSC resource.

- Is there a reason why the knocking out key is added to the result?
- When should it been removed? After the merge, while merging?
- How does knockout work with more than two layers / how is it supposed to work?
