### ISSUE TITLE
Knockouts don't work for: Hashtable Arrays

### ISSUE THREAD

**Issue by raandree** [gaelcolas/datum#129]
Even more important than knocking out keys would be knowing out hash tables from a hash table array, similar like removing knocking out values from a base type array. This behavior is not available in Puppet.

Lower Level:
```yml
HashTables:
  Items:
    - Key1: h3
      Key2: 3
      Key3: v
    - Key1: h4
      Key2: 4
    - Key1: h5
      Key2: 5
```

Higher Level:
```yml
HashTables:
  Items:
    - Key1: h1
      Key2: 1
    - Key1: h2
      Key2: 2
    - Key1: --h3
      Key2: 3
      Key3: v3
```

Actual RSOP:
```yml
HashTables:
  Items:
  - Key1: h1                                                                                  AllNodes\Dev\DSCFile01
    Key2: 1                                                                                   AllNodes\Dev\DSCFile01
  - Key1: h2                                                                                  AllNodes\Dev\DSCFile01
    Key2: 2                                                                                   AllNodes\Dev\DSCFile01
  - Key3: v3                                                                                  AllNodes\Dev\DSCFile01
    Key1: --h3                                                                                AllNodes\Dev\DSCFile01
    Key2: 3                                                                                   AllNodes\Dev\DSCFile01
  - Key3: v                                                                                         Roles\FileServer
    Key1: h3                                                                                        Roles\FileServer
    Key2: 3                                                                                         Roles\FileServer
  - Key1: h4                                                                                        Roles\FileServer
    Key2: 4                                                                                         Roles\FileServer
  - Key1: h5                                                                                        Roles\FileServer
    Key2: 5                                                                                         Roles\FileServer
```

Expected RSOP:
```yml
HashTables:
  Items:
  - Key1: h1                                                                                  AllNodes\Dev\DSCFile01
    Key2: 1                                                                                   AllNodes\Dev\DSCFile01
  - Key1: h2                                                                                  AllNodes\Dev\DSCFile01
    Key2: 2                                                                                   AllNodes\Dev\DSCFile01
  - Key1: h4                                                                                        Roles\FileServer
    Key2: 4                                                                                         Roles\FileServer
  - Key1: h5                                                                                        Roles\FileServer
    Key2: 5                                                                                         Roles\FileServer
```

Datum.yml
```yml
  HashTables:
    merge_hash: deep
  HashTables\Items:
    merge_hash_array: UniqueKeyValTuples
    merge_options:
      tuple_keys:
        - Key1
        - Key2
      knockout_prefix: --
```

Instead of knocking out the hash table with the with `Key1 == h3`, Datum treats it as a new hash table to merge as `Lower Level->Key1` is different from `Higher Level->Key1`.

- How does knockout work with more than two layers / how is it supposed to work?
- Is it sufficient to allow a knockout only on the first key in `merge_options->tuple_keys`
