### ISSUE TITLE
Datum Merge use case: deep + knockout prefix

### ISSUE THREAD

**Issue by gaelcolas** [gaelcolas/Datum#13]
```yaml
Node:
  Role1:
    Subkey1:
      c: 3
      --d: NULL
#+++++++++++++++++
Roles:
  Role1:
    Subkey1:
      a: 1
      b: 2
      d: 666
#=================
Result:
  Role1:
    Subkey1:
      a: 1
      b: 2
      c: 3

### Datum.yml 
lookup_options:
  Role1\Subkey1:
    merge:
      strategy: deep
      knockoutPrefix: --
```
