### ISSUE TITLE
Datum.yml - Specify a directory to load all files

### ISSUE THREAD

**Issue by rcfmartin** [gaelcolas/datum#137]
# Problem
I have a directory with multiple yaml files to configure a load balancer. Each file contains the configuration for a single domain.
E.g.
```
Domains
├── example.com.yml
└── contoso.com.yml
```
The `lookup_options` for the configuration is set to `deep`, so it creates a hash array instead of merging the configuration based on the most specific. 

At the moment my `Datum.yml` looks like below.
```yaml
ResolutionPrecedence:
  - Domains\example.com
  - Domains\contoso.com
  ```

# Question
Since I'm just appending the configuration instead or merging it, Is there a way to specify just the directory and have datum resolve all files in that directory? Something like the below.
### Example
```yaml
ResolutionPrecedence:
  - Domains\*.yml
  ```

**Comment by rcfmartin** [comment]
Please disregard this issue. I created a task to add configuration file dynamically during the build process.

**Comment by raandree** [comment]
I'm just curious. Normally a node belongs to a domain and you want to take the settings from the yaml file of that domain. What is the use case to read the settings from two or even more domains?

**Comment by rcfmartin** [comment]
@raandree let me explain what I'm doing.
# The layout
 I'm using the [dscworkshop](https://github.com/dsccommunity/DscWorkshop) as a starting point. 

My current build creates and deploys an active directory domain which includes 2 Domain Controllers, DHCP Server, File Server, and a Windows 10 Workstation.

So the current folder structure looks something like the below
```shell
Source
│   Datum.yml
│   DscWorkshop.psd1
│   DscWorkshop.psm1
│   ExternalData.csv
│
├───AllNodes
│   └───Test
│           DC01.yml
│           DC02.yml
│           DHCP01.yml
│           FS01.yml
│           WS01.yml
│
├───Baselines
│       DomainController.yml
│       DscLcm.yml
│       Security.yml
│       Server.yml
│       Workstation.yml
│
├───Environment
│       Dev.yml
│       Prod.yml
│       Test.yml
│
├───Global
│       Azure.yml
│       Domain.yml
│
├───Locations
│       HQ.yml
|
│
├───Roles
│       DhcpServer.yml
│       DomainController.yml
│       FileServer.yml
│       WebServer.yml
│       Workstation.yml
```

# The "Issue"
It took me while but I got to the point where I can comfortably deploy and manage a windows environment with dsc. The only issue is that I often have to work within a linux environment, and the current deployment was meant to work with windows endpoints.
Since the deployment works so well with the pipeline, I decided to expand the project and add support for linux configurations instead of working with other tools such as ansible, chef, puppet, etc... Instead, the deployment would use something like `Posh-SSH` to apply the configuration. (In this case my vm templates have been pre-configured with powershell, but just deploying a bash or python script would work the same way)

In this case I created another layer that defines the Operating System (Currently `Linux` and `Windows`). For the windows nodes, the build stays the same. For the linux nodes however, depending on the configuration I need Datum to behave a little differently than the default.

Let's say I want to configure [HAProxy](https://www.haproxy.com) on a Debian server. The haproxy configuration would look something like the below

```
global
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s

defaults
    mode http
    timeout client 10s
    timeout connect 5s
    timeout server 10s
    timeout http-request 10s
    errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http
    
frontend stats
    bind :8000
    stats enable
    stats uri /monitoring
    stats auth username:password

frontend my_frontend
    bind *:80
    default_backend api.example.com

backend api.example.com
    balance leastconn
    server server1 127.0.0.1:8001
    
backend dashboard.contoso.com
    balance leastconn
    server server1 127.0.0.1:8002

```

Based on the config above, my `HAProxy.yml` file would look like below
New Layer `Configuration`
```bash
├───AllNodes
│   └───Test
├───Baselines
├───Configuration
│   └───HAProxy.yml
├───Environment
├───Global
├───Locations
├───Roles
└───TestRsopReferences
```
Contents of `HAProxy.yml`
```yml
Configurations:
- HAProxyConfig

HAProxyConfig:
  Global:
    stats:
    - 'socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners'
    - 'timeout 30s'
    user: 'haproxy'
    group: 'haproxy'
    daemon: True

  Defaults:
    mode: 'http'
    timeout:
    - 'connect 5000'
    - 'client 50000'
    - 'server 50000'

    errorfile:
    - '400 /etc/haproxy/errors/400.http'
    - '403 /etc/haproxy/errors/403.http'
    - '408 /etc/haproxy/errors/408.http'
    - '500 /etc/haproxy/errors/500.http'
    - '502 /etc/haproxy/errors/502.http'
    - '503 /etc/haproxy/errors/503.http'
    - '504 /etc/haproxy/errors/504.http'

  Frontend:
  - Name: stats
    bind: ':8000'
    stats:
    - 'enable'
    - 'uri /monitoring'
    - 'realm HAProxy\ Statistics'
    - 'auth admin:password' # The password would be encrypted by datum. [ENC=PE9ianMgVmVyc2lvbj0iMS4xLjAuMSIgeG1sbnM9Imh0dHA6==]
  - Name: my_frontend
    bind: '*:80'
    default_backend: 'example'
  
  Backend:
  - Name: 'api.example.com'
    balance: 'leastconn'
    target:   127.0.0.1
    port: 8001
  - Name: 'dashboard.contoso.com'
    balance: 'leastconn'
    target:   127.0.0.1
    port: 8002
```

As you can see above, I can have multiple `Frontends` and `Backends`. The issue here is that I'm managing multiple domains within the same configuration file. As the file grows larger, it becomes difficult to manage each domain. The solution, similar to all the other configuration files, I broke them down into different files. So the new tree looks like the below
```bash
├───AllNodes
│   └───Test
├───Baselines
├── Configuration
│   │   └── HAProxy
│   │       ├── Domains
│   │       │   ├── contoso.com.yml
│   │       │   ├── example.com.yml
│   │       └── HAProxy.yml
├───Environment
├───Global
├───Locations
├───Roles
└───TestRsopReferences
```
The `HAProxy.yml` file contains objects that are unique. e.g. `global`, `defaults` 
```yaml
# HAPRoxy.yml
Configurations:
- HAProxyConfig

HAProxyConfig:
  Global:
    stats:
    - 'socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners'
    - 'timeout 30s'
    user: 'haproxy'
    group: 'haproxy'
    daemon: True

  Defaults:
    mode: 'http'
    timeout:
    - 'connect 5000'
    - 'client 50000'
    - 'server 50000'

    errorfile:
    - '400 /etc/haproxy/errors/400.http'
    - '403 /etc/haproxy/errors/403.http'
    - '408 /etc/haproxy/errors/408.http'
    - '500 /etc/haproxy/errors/500.http'
    - '502 /etc/haproxy/errors/502.http'
    - '503 /etc/haproxy/errors/503.http'
    - '504 /etc/haproxy/errors/504.http'
  Frontend:
  - Name: stats
    bind: ':8000'
    stats:
    - 'enable'
    - 'uri /monitoring'
    - 'realm HAProxy\ Statistics'
    - 'auth admin:password' # The password would be encrypted by datum. [ENC=PE9ianMgVmVyc2lvbj0iMS4xLjAuMSIgeG1sbnM9Imh0dHA6==]
  - Name: my_frontend
    bind: '*:80'
    default_backend: 'example'
```
The `example.com.yml` and `contoso.com.yml` contain objects that can be applied to different domains, similar to how we have multiple nodes that can have different variations of the same object. The example below only shows the `Backend`, but the same concept applies to the `Frontend`
```yaml
# example.com.yml
Configurations:
- HAProxyConfig

HAProxyConfig:
  Backend:
  - Name: '[x={ "api.$($File.BaseName)" } =]'
    balance: 'leastconn'
    target:   127.0.0.1
    port: 8001
  - Name: '[x={ "metrics.$($File.BaseName)" } =]'
    balance: 'leastconn'
    target:   127.0.0.1
    port: 9001
```

```yaml
# contoso.com.yml
Configurations:
- HAProxyConfig

HAProxyConfig:
  Backend:
  - Name: '[x={ "dashboard.$($File.BaseName)" } =]'
    balance: 'leastconn'
    target:   127.0.0.1
    port: 8002
  - Name: '[x={ "admin.$($File.BaseName)" } =]'
    balance: 'leastconn'
    target:   127.0.0.1
    port: 9002
```

Now that we have an understanding of the setup, let's move on to the `Datum.yml`
In order for the HAProxyConfig to make it to the final RSOP, I need to specify the paths under `ResolutionPrecedence`. While specifying 2 files is not a problem, I work in an environment that manages 200+ domains, and specifying them line by line was not ideal. 
```yaml
ResolutionPrecedence:
  - Configuration\HAProxy\Domains\example.com
  - Configuration\HAProxy\Domains\contoso.com
```

Since I don't quite fully understand how the `lookup_options` work, this is how I currently have it setup.
```yaml
lookup_options:
  Configurations:
    merge_basetype_array: Unique
  HAProxyConfig:
    merge_hash: deep
  HAProxyConfig/Backend: deep
  HAProxyConfig/Frontend: deep
```
Notice that I have the `Backend` and `Frontend` set to `deep` so it appends the configuration instead of merging it based on MostSpecific.
# The Question
Is there a way to just specify a directory under `ResolutionPrecedence` so that any configuration file in that directory will end up in the RSOP based on the lookup_options? For example
```yaml
ResolutionPrecedence:
  - AllNodes\$($Node.Environment)\$($Node.NodeName)
  - Environment\$($Node.Environment)
  - Locations\$($Node.Location)
  - Roles\$($Node.Role)
  - Baselines\Security
  - Baselines\$($Node.Baseline)
  - Baselines\DscLcm
  - Configuration\HAProxy\* # Anything under HAProxy will end up in the rsop based on the lookup_options 
```

I just need those files to be merged, and I have not been able to figure out a good way to either:
- Create a dependency from a Role
	- Any node that has a role that requires HAProxy configured, would automatically merge the files under configuration
- Find a way to create an RSOP just for HAProxy configuration, which I was able to achieve by creating a node and adding each file of the configuration layer under `ResolutionPrecedence`
Please let me know if all of that makes sense.
