### ISSUE TITLE
Datum merge use case: deep + ko prefix + array unique merge

### ISSUE THREAD

**Issue by gaelcolas** [gaelcolas/Datum#14]
```yaml
Node:
  Role1:
    Subkey1:
      b:
        - val1
        - val2
      c: 3
      --d: NULL

#+++++++++++++++++
Roles:
  Role1:
    Subkey1:
      a: 1
      b:
      - val3
      - val4
      d: 666

#=================
Result:
  Role1:
    Subkey1:
      a: 1
      b:
      - val1
      - val2
      - val3
      - val4
      c: 3

### Datum.yml 
lookup_options:
  Role1\Subkey1:
    merge:
      strategy: deep
      knockoutPrefix: --
  Role1\Subkey1\b:
      strategy: UniqueItems
```
