### ISSUE TITLE
Datum Merge use case: Addition to hashtable[] unique per property name with knockout prefix

### ISSUE THREAD

**Issue by gaelcolas** [gaelcolas/Datum#15]
```yaml
Node:
  SoftwareBase:
    Sources: #to test disabling this source on that node
      - Name: chocolatey.licensed
        Disabled: true
        Source: https://chocolatey,licensed.org/api/v2
      - Name: --testToRemove

#+++++++++++++++++
Roles:
  SoftwareBase:
    Sources:
      - Name: chocolatey
        Disabled: false
        Source: https://chocolatey.org/api/v2
      - Name: testToRemove
        Disabled: false
        Source: https://proget/nuget/choco

#=================
Result:
  SoftwareBase:
    Sources: #to test disabling this source on that node
      - Name: chocolatey.licensed
        Disabled: true
        Source: https://chocolatey,licensed.org/api/v2
      - Name: chocolatey
        Disabled: false
        Source: https://chocolatey.org/api/v2

### Datum.yml 
lookup_options:
  SoftwareBase\Sources:
    merge: 
      strategy: ArrayOfUniqueHashByPropertyName
      hashMerge: deep #override/hash/deep?
      PropertyName: Name
      knockoutPrefix: -- #will be matched for PropertyName
```
