### ISSUE TITLE
Datum to reference another Datum datum path

### ISSUE THREAD

**Issue by gaelcolas** [gaelcolas/Datum#19]
Some Config Data should not or cannot be saved at the correct place of the hierarchy (i.e. a config file, or certificate used as a parameter to a Configuration):

```yaml
MyResource:
  CN: MyCN
  Certificate: "<blob of file content>"
```
Managing the certificate in-line is not convenient, the file should probably be in it's own 'provider' or mounted somewhere else in the Datum Tree ($Datum.Files.certificates.MyResourceCert).

That means the data structure for `MyResource` should have the certificate file 'linked' to the Certificate key of the config Data, like so (in a similar pattern that of Secure Datum):

```yaml
MyResource:
  CN: MyCN
  Certificate: "[REF=[Files\certificates\MyResourceCert]]"
```

Now, during a lookup $Node 'MyResource', Datum should resource the following hashtable, resolving under the hood the file content (or following what looks like a redirection):
```PowerShell
@{
    CN = 'MyCN'
    Certificate = 'blob of file content'
}
```
