### ISSUE TITLE
Improve Merging definitions

### ISSUE THREAD

**Issue by gaelcolas** [gaelcolas/Datum#23]
The current merging parameters is a bit messy, and could be improved to look like this:
```yaml
lookup_options:
  MergeTest1:
    merge_options:
      knockout_prefix: --
      PropertyNames:
        - name
        - version
    merge_hash: 
      strategy: MostSpecific|Hash|Deep
    merge_basetype_arrays: 
      strategy: Unique|Sum
    merge_hash_arrays:
      strategy: UniqueTuple|DeepTuple|Sum
```

That would also allow to simplify and clarify the code underneath.
As this will be a breaking change, it should be done before v1.0 release.
