### ISSUE TITLE
make the building of rsop nodes declarative

### ISSUE THREAD

**Issue by gaelcolas** [gaelcolas/Datum#35]
find a way to declare how to get the nodes and load their RSOP in the configdata variable.

So far, the best I found is this:
```yaml
Variables:
  ConfigurationData:
    AllNodes:
	  Path: Datum:\AllNodes\#{Environment}\#{Name}
	Datum:
	  Path: Datum:\
	  
ConfigurationData:
  AllNodes:
    - 
```

The main goals are to:
- define where to find the $Nodes in the hierarchy
- what path metadata to be loaded (#{property} or * to not include it)
