### ISSUE TITLE
Examples for DatumHandlers available?

### ISSUE THREAD

**Issue by kinwolfqc** [gaelcolas/Datum#64]
Hi,
  Is there a complete example of how to use the DatumHandler feature?  We need to be able to inject variable in the yaml at built time (we need to be able to use a function that get passwords out of SecretServer and inject the result in the yml.) and the Handler seems the way to do it, but I admit it's a bit advanced for my Powershell skills and so far I never got it to work.

**Comment by gaelcolas** [comment]
We were doing just that at last job, loading Secret Server credentials into config.

This example shows how to use the built-in test handler (but does nothing useful)
https://github.com/gaelcolas/Datum/blob/master/Datum/tests/Integration/assets/DSC_ConfigData/Datum.yml#L31L35

And this is an example of a module with a Handler: https://github.com/gaelcolas/Datum.ProtectedData
You just need to implement 2 functions in your module:
`Test-$$$Filter`
`Invoke-$$$Action`
Where `$$$` is your handler name...
Then, make your module available (i.e. by adding to the PSDepend file) or installing module, and add this to `Datum.yml`

```yaml
DatumHandlers:
  moduleName::$$$:
    CommandOptions:
      Param1: value1 #optional
```

**Comment by gaelcolas** [comment]
I also documented other use case of handlers here: https://github.com/gaelcolas/Datum/blob/master/docs/Datum_Redirections.md

**Comment by gaelcolas** [comment]
Let me know where you struggle, and I might do and share a secret server handler if I get a chance.

**Comment by kinwolfqc** [comment]
To try to understand the handler, I created a module named DatumSecretServer with a test fonction and the invoke function that simply return back what was send to it.(we have a fully functional module with functions for SecretServer, but I wanted to test with a dummy first to be sure)  It looks like the test function is never called, or never return True, so I'm obviously doing something wrong.

In `datum.yml` 
```
 DatumHandlers:
    DatumSecretServer::Secrets:
      CommandOptions:
        url:  "https:\\\\www.secretserver.url\\SecretServer"
```
The module content of `DatumSecretServer.psm1` is:
```
function Test-SecretsFilter {
    Param(
        [Parameter(
            ValueFromPipeline
        )]
        $InputObject
    )

    $InputObject -is [string] -and $InputObject.Trim() -match "^\[SEC=[\w\W]*\]$"
}

function Invoke-SecretsAction {
    Param (
        [Parameter(
            ValueFromPipeline
        )]
        [ValidateNotNullOrEmpty()]
        [string]
        $id,
        
        [Parameter(
            Mandatory
            , ValueFromPipeline
            , ValueFromPipelineByPropertyName
        )]
        [ValidateNotNullOrEmpty()]
        [string]
        $url
    )

    $id = " $id and $url"
    return $id

}
```

and the yml that has the id value

```
Configurations:
  - AppPools 

AppPools:
  Values:
    - Name: .Net v2.0
      Ensure: Absent
    - Name: .Net v2.0 Classic
      Ensure: Absent
    - Name: BENAppPool
      restartPrivateMemoryLimit:  393216
      restartTimeLimit: 00:00:00
      id: '[SEC=dev\username]'
      pingInterval: 00:00:10
      loadBalancerCapabilities: TcpLevel
      State:  Started
      identityType: SpecificUser
      rapidFailProtection:  FALSE
      Ensure: Present
```
