### ISSUE TITLE
A hash table can only be added to another hash table

### ISSUE THREAD

**Issue by raandree** [gaelcolas/Datum#67]
@gaelcolas, can you have a look at brach https://github.com/AutomatedLab/DscWorkshop/tree/HashTableMergeIssue of DscWorkshop. I have added the following configuration to the DSCFile01 node which leads to the conflict:

``` yaml
FilesAndFolders:
  Items:
    - DestinationPath: C:\TestFolderInDev
      Type: Directory
```

and that's the merge behavior:

``` yaml
lookup_options:
  Configurations:
    merge_basetype_array: Unique
  
  FilesAndFolders:
    merge_hash: deep

  FilesAndFolders\Items:
    merge_hash_array: DeepItemMergeByTuples
```
 Am I doing something wrong or is this a bug?
