### ISSUE TITLE
Datum throws warning when you use hash_array and edit data on three levels

### ISSUE THREAD

**Issue by ykuijs** [gaelcolas/datum#88]
When you use a hash_array to configure data and then edit data on three or more different levels, Datum throws a warning and only uses the data from the highest two levels.

```
SSLCertificateImport:
    merge_hash: deep
  SSLCertificateImport\Certificates:
    merge_basetype_array: Deep
    merge_hash_array: DeepTuple
    merge_options:
      tuple_keys:
        - Name
```

If you then edit the data of this composite resource on level 1 and add data on level 2 and 3, the following error is displayed:
```
WARNING: Cannot merge different types in path 'SSLCertificateImport\Certificates' REF:[hashtable] | DIFF:[hash_array]System.Object[] , returning most specific Datum.
```

**Troubleshooting info**

_Data Level 1_
```
SSLCertificateImport:
  Certificates:
    - Name: SSLCertificate
      Location: LocalMachine
      Store: My
      Exportable: True
      Ensure: Present
```

_Data Level 2_
```
SSLCertificateImport:
  Certificates:
    - Name: SSLCertificate
      Ensure: Absent
```

_Data Level 3_
```
SSLCertificateImport:
  Certificates:
    - Name: SSLCertificate
      Thumbprint: A1B2C3D4E5F6
```

_Actual result_
```
SSLCertificateImport:
  Certificates:
    - Name: SSLCertificate
      Ensure: Absent
      Thumbprint: A1B2C3D4E5F6
```

_Expected result_
```
SSLCertificateImport:
  Certificates:
    - Name: SSLCertificate
      Location: LocalMachine
      Store: My
      Exportable: True
      Ensure: Absent
      Thumbprint: A1B2C3D4E5F6
```

**Reproduction**
If you download the following [zip file](https://github.com/gaelcolas/datum/files/5501540/DscConfigData.zip) and run the below commands, the first command will work (SPApplication.yml does not contain data) and the second with show the issue (SPSearchBackEnd.yml does contain data.

Level 1: SharePointServer.yml
Level 2: SPSearchBackEnd.yml
Level 3: StandardAcceptancePrimary.yml

```PowerShell
$datum = New-DatumStructure -DefinitionFile .\Datum.yml

$srvApp = $datum.AllNodes.Standard.Acceptance.Primary.ServerApp
$dataApp = Lookup -Node $srvApp -DatumTree $datum -PropertyPath 'SSLCertificateImport'
$dataApp.Certificates

$srvSbe = $datum.AllNodes.Standard.Acceptance.Primary.ServerSbe
$dataSbe = Lookup -Node $srvSbe -DatumTree $datum -PropertyPath 'SSLCertificateImport'
$dataSbe.Certificates
```

**Solution**
I found that this issue is caused by the fact that PowerShell doesn't return an array when it only contains one item. This is causing the module later on to try to compare a hashtable with an array. By changing line 606 in Datum.psm1 by the following code the issue is fixed, forcing the item to be stored as an array:
```PowerShell
                    if ($clonedReference.$currentKey -is [System.Array])
                    {
                        [System.Array]$clonedReference[$currentKey]  = Merge-Datum @MergeDatumParams
                    }
                    else
                    {
                        $clonedReference[$currentKey]  = Merge-Datum @MergeDatumParams
                    }
```

Is this a good solution or do you see a different (better) solution?
