### ISSUE TITLE
Error using Datum Handler / Datum handlers cannot work with arrays

### ISSUE THREAD

**Issue by raandree** [gaelcolas/datum#89]
If you have strings in an array that are catched up by a Datum handler, you get this error, as the Datum handler expects a string.

```
WARNING: Error using Datum Handler Datum.InvokeCommand::InvokeCommand, returning Input Object
```

The result is pretty malformed data in the RSOP. The following array looks like this then:
```yml
TestArray1:
  - '[x={ Get-Random }]'
  - '[x={ Get-Random }]'
```

```yml
TestArray1:
- '[x={ Get-Random }]'
- value:
  - 196783108
  - 685218656
  Count: 2
- value:
  - 1621033775
  - 327351527
  Count: 2
```

In almost any projects we want to use the handler [Datum.InvokeCommand](https://github.com/raandree/Datum.InvokeCommand) also on arrays.

I have published a working demo of the issue: https://github.com/raandree/DscWorkshop/tree/test/DatumHandlerArrayBug
The same demo with the fix added to Datum: https://github.com/raandree/DscWorkshop/tree/test/DatumHandlerArrayBugFix
